# Generated by Django 5.1 on 2024-11-19 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg', '0002_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('email_address', models.CharField(max_length=250)),
                ('address_first', models.CharField(max_length=500)),
                ('address_second', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=200)),
                ('phone_number_code', models.CharField(max_length=50)),
                ('goal', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('main_language', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=64)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
